# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123qwe
      POSTGRES_DB: news_portal
    ports:
      - 5432:5432

#   TODO: Install pgadmin
#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080